# Generated by Django 2.1.3 on 2018-11-22 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
    ]
