# Generated by Django 2.1.3 on 2018-11-22 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20181122_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='articlecategory',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='ArticleCategory',
        ),
        migrations.DeleteModel(
            name='ArticleTag',
        ),
    ]
